### ISSUE TITLE
Two broken extra entries for geometry in Boost online documentation (since 1.70)

### ISSUE THREAD

**Issue by tinko92** [boostorg/geometry#585]
I noticed (with the release of 1.70) that two extra entries showed up in the online Boost HTML documentation, titled "Geometry Extensions" and "Geometry Index" that share the description with the "Geometry" entry, however, the links lead to 404 errors:

New entries:
https://www.boost.org/doc/libs/1_70_0/#lib-geometry-extensions
https://www.boost.org/doc/libs/1_70_0/#lib-geometry-index

Targets with 404 errors:
https://www.boost.org/doc/libs/1_70_0/libs/geometry/extensions/doc/html/index.html
https://www.boost.org/doc/libs/1_70_0/libs/geometry/index/doc/html/index.html

**Comment by awulkiew** [comment]
Right, I feared that something like this would happen. It was caused by solution to this issue: https://github.com/boostorg/geometry/issues/575
and addition of metadata for "sublibs" in order to silence the regression testing suite.

**Comment by awulkiew** [comment]
@mloskot In case you wanted to do the same for GIL. This is the result. :)

**Comment by awulkiew** [comment]
It seems I also made a mistake and pushed extensions directory into master.

**Comment by Kojoley** [comment]
Are they completely undocumented? Otherwise you can setup a redirection to a correct page.

**Comment by awulkiew** [comment]
I did do that but it it seems it didn't work. It's possible that the path is wrong I guess.

It's also questionable should these be on the list of libraries since technically they are not sub-libraries.

**Comment by awulkiew** [comment]
@Kojoley AFAICT redirect is the same as the one in Spirit and Functional:
https://github.com/boostorg/geometry/blob/develop/index/index.html
https://github.com/boostorg/spirit/blob/develop/repository/index.html
https://github.com/boostorg/functional/blob/develop/factory/index.html

**Comment by awulkiew** [comment]
My understanding is that redirections in documentation are unrelated to the script generating this list:
https://www.boost.org/doc/libs/1_70_0

**Comment by Kojoley** [comment]
Spirit sublibs has documentation https://github.com/boostorg/spirit/tree/develop/repository/doc/html, in your case you need to redirect backwards `../doc/html/index.html`

**Comment by awulkiew** [comment]
Do you know of a way of testing it or do we have to wait for the next release?

**Comment by awulkiew** [comment]
And thanks for the help. It seems that it should work.

**Comment by Kojoley** [comment]
Generate the documentation (`b2 html`) and just open the `index.html` in your browser.

**Comment by Kojoley** [comment]
> do we have to wait for the next release

No, the docs are build on every commit by CI in the main repo.

**Comment by awulkiew** [comment]
Interesting. Ok, I'll handle it today.

**Comment by Kojoley** [comment]
I do not know how it is working, but the list generator has `hidden` libraries https://github.com/boostorg/website/blame/master/doc/libraries.json.php#L15-L21

**Comment by awulkiew** [comment]
`is_hidden()` is implemented here I think:
https://github.com/boostorg/website/blob/master/common/code/boost_version.php#L250

**Comment by Kojoley** [comment]
Did not see your edit.
It is per library. To use it, put `"status": "hidden"` or `"boost-version": "hidden"` in a manifest. What I was saying in my previous message that I do not know the consequences of doing that.

**Comment by awulkiew** [comment]
Ok, I'll try that after seeing changes for the current version reflected on the libraries list for develop branch. Thanks.

**Comment by awulkiew** [comment]
@Kojoley I tried setting `status` and both `status` and `boost-version` to `hidden` but sublibs are still on the list.

**Comment by mloskot** [comment]
There have been changes related to this issue and the current situation is this:

1. Boost `develop` docs only include https://www.boost.org/doc/libs/develop#lib-geometry

2. Boost `master` docs no longer include the `#lib-geometry-index` but still include the https://www.boost.org/doc/libs/master#lib-geometry-extensions
    I suspect, this is due to the fact Geometry's `develop` has not been fully merged to `master` and once the merge happens, the `#lib-geometry-extensions` should be gone as well.

Question is, if there is going to be `develop` to `master` merge before [closure of Boost 1.73 for major changes](https://lists.boost.org/Archives/boost/2020/03/248524.php).

**Comment by awulkiew** [comment]
@mloskot All changes related to sublibs metadata were already merged into master. The master branch does not have extensions directory at all. By mistake I pushed extensions directory only with metadata into master at some point but I removed it later.

So I don't know what's happening there. Does it pick up the sublibs directories from develop branch but then metadata from master branch? Is this documented anywhere? This thing starts to annoy me and I'm strongly considering removing all of the metadata from the sublibs directories and to go back to ignoring the related regression matrix errors.

**Comment by mloskot** [comment]
@awulkiew I have no idea what is going on, how it works, but I've just asked for help here [[geometry] Global Boost documentation for master not refreshed?](https://lists.boost.org/Archives/boost/2020/03/248531.php)

**Comment by mloskot** [comment]
My thread has received no answers and the problem is still happening in 1.73 beta1:

1. Go to https://lists.boost.org/Archives/boost/2020/04/248687.php
2. Download `boost_1_73_0_b1.7z`
3. Unpack and load `boost_1_73_0/index.html`
4. Go to `boost_1_73_0/libs/libraries.htm`
5. Hit the "Geometry Extensions" link
6. Loaded is `/boost_1_73_0/libs/geometry/extensions/index.html` which does not exist

I'm going to re-ask on the mailing list.

**Comment by tinko92** [comment]
The following observations are not backed by a complete understanding of the website and the way it is updated, but the following observations based on trying to run the website locally may be helpful:
Consider https://www.boost.org/doc/libraries.xml , which I believe is generated using https://github.com/boostorg/website/blob/master/site-tools/update-doc-list.php :
We find: 
- geometry/extensions, update version 1.70, not hidden
- geometry/extensions, update version develop, hidden
- geometry/index, update version 1.70, not hidden
- geometry/index, later update versions, hidden

In the documentation we find:
- version 1.70: extensions and index show up
- version 1.72: extensions shows up, index does not

running https://github.com/boostorg/website/blob/master/doc/generate.php locally and manually inserting an entry into $libs for version 1.72 or 1.73 with extensions and status hidden, makes the entry go away in my local output of https://www.boost.org/doc/generate.php?page=libs/libraries.htm&version=1.73 .

This suggests, that for releases the latest metadata from a release version is used. So having 1.70 for the latest metadata and having none after that may be the issue. Maybe if there was metadata for extensions with status hidden in release 1.73, that would make it go away for future releases.

**Comment by tinko92** [comment]
Minor followup. By applying the following steps I was able to make the "geometry/extension" disappear in the output of generate.php?page=libs/libraries.html&version=1.72 : 
1. clone boostorg/website, set it up with local mirrors of all boost repositories on local webserver
2. clone local mirror of boostorg/boost.git recursively, commit and push this change ( https://github.com/boostorg/geometry/compare/master...tinko92:fix/doc_extension , I don't know if this would have other side-effects, so I didn't create a PR yet) to geometry-submodule
3. tag it as 1.72 (overwriting old tag) in the superproject, push superproject, run site-tools/update-doc-list.php on local mirrors of repository on branch master
4. run generate.php?page=libs/libraries.htm&version=1.72  --> no geometry extension entry.

So, I believe if the meta data would be added like in my branch linked above, and be in the tag for 1.73 in the superproject, then this would get rid of the entry. Caveat: I don't know if those metadata is used for other purposes than making lists of libraries, so my proposed fix may be invalid.

**Comment by glenfe** [comment]
https://github.com/boostorg/website/commit/d8c79ba5cb78729cfe02bfbecd9a74f834de7b9f and https://github.com/boostorg/website/commit/8d463e641c6007acd128ee14bf08070c4dbd08c3 .
